Repository 3Tecnos-Development/nosql-easy, pull requests merged in 2020-09, with the labels that each got.

#1 Generate patch version
  README.md
Labels: PR: unreviewed, release:patch

#2 Generate Patch NPM
  .github/workflows/npm-publish.yml
  .github/workflows/release-tag.yml
  .gitignore
  .npmignore
  package.json
Labels: PR: unreviewed, release:patch

#3 Adjusting dependency
  .npmignore
Labels: PR: unreviewed, release:patch

#4 Adjusting dependecy src
  .npmignore
Labels: PR: unreviewed, release:patch

#5 Add @firebase/firestore-types dependecy
  package-lock.json
  package.json
Labels: PR: unreviewed, release:patch

#6 Remove src and node_modules
  .npmignore
Labels: PR: unreviewed, release:patch

#7 Preparing to use in package
  __tests__/integration/NoSqlEasy.test.ts
  src/Config.ts
  src/dialects/Firestore/FirestoreRepository.ts
  src/dialects/Firestore/interfaces/IFirestoreCredential.ts
  src/index.ts
  src/interfaces.ts
  src/types.ts
  src/types/DialectType.ts
  src/types/Options.ts
  src/types/OrderBy.ts
  src/types/Where.ts
Labels: PR: unreviewed, release:patch

#8 Add method size collection
  README.md
  src/Config.ts
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
Labels: PR: reviewed-approved, release:patch

#9 Adjust dynamic types of the objects
  src/dialects/Firestore/FirestoreRepository.ts
  src/types/OrderBy.ts
  src/types/Where.ts
Labels: PR: reviewed-approved, release:patch

#10 Updating the documentation to "update" method and generating package npm
  README.md
Labels: PR: reviewed-approved, release:patch

#11 add method to paginate data collection, tests and workflows tests
  .env.example
  .github/workflows/test.yml
  README.md
  __tests__/integration/NoSqlEasy.test.ts
  package-lock.json
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
Labels: PR: reviewed-approved, release:minor

#12 Adjusting signature to method "getPaginatedCollection" in the documen…
  README.md
Labels: PR: partially-approved, release:minor

#13 Change default bump version scheme to "minor"
  .github/workflows/release-tag.yml
Labels: PR: reviewed-approved

#14 Just to force generate version in worflow
  .github/workflows/release-tag.yml
  .github/workflows/test.yml
Labels: PR: reviewed-approved, release:patch

#15 create method to remove element in array
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
Labels: PR: reviewed-approved, release:minor
