Repository 3Tecnos-Development/nosql-easy, pull requests merged in 2020-11, with the labels that each got.

#16 feature: add feature for nested objects
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
  src/types.ts
  src/types/FieldNested.ts
  src/types/Options.ts
  src/types/Where.ts
Labels: PR: partially-approved, release:patch

#17 refactor: rename property of type where in getCollection
  src/dialects/Firestore/FirestoreRepository.ts
Labels: PR: reviewed-approved, release:patch

#18 fix: convert the value parameter to the json object in updateField
  src/dialects/Firestore/FirestoreRepository.ts
Labels: PR: reviewed-approved, release:patch

#19 refactory: adjust in method insert for return another generic type
  .github/workflows/test.yml
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
Labels: PR: partially-approved, release:minor

#20 fix:method insert update
  src/index.ts
Labels: PR: reviewed-approved, bug, release:patch
