Repository 3Tecnos-Development/nosql-easy, pull requests merged in 2021-03, with the labels that each got.

#29 chore: add replace(/\\n/g, "\n")
  src/dialects/Firestore/FirestoreRepository.ts
Labels: PR: unreviewed

#30 feat: add two credentials approaches
  src/dialects/Firestore/FirestoreRepository.ts
Labels: PR: unreviewed, release:patch

#31 feat: add base64
  src/dialects/Firestore/FirestoreRepository.ts
Labels: PR: unreviewed, release:patch

#32 Bugfix/return undefined when object is empty
  src/dialects/Firestore/FirestoreRepository.ts
  src/helpers/emptyToUndefined/emptyToUndefined.ts
  src/helpers/index.ts
  src/tests/integration/NoSqlEasy.spec.ts
Labels: PR: partially-approved, release:patch
