Repository 3Tecnos-Development/nosql-easy, pull requests merged in 2021-05, with the labels that each got.

#35 Feature/filter
  .eslintrc.json
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/dialects/Firestore/helpers/add-order-by-to/add-order-by-to.ts
  src/dialects/Firestore/helpers/doc-to-model/doc-to-model.ts
  src/dialects/Firestore/helpers/filter-conditions-by-operators/filter-conditions-by-operators.ts
  src/dialects/Firestore/helpers/filter-to-where/filter-to-where.ts
  src/dialects/Firestore/helpers/get-conditional-queries/get-conditional-queries.ts
  src/dialects/Firestore/helpers/get-credentials/get-credentials.ts
  src/dialects/Firestore/helpers/group-conditions-by-compound-queries/group-conditions-by-compound-queries.ts
  src/dialects/Firestore/helpers/index.ts
  src/dialects/Firestore/helpers/intersect-models/intersect-models.ts
  src/helpers/dynamic-sort-multiple/dynamic-sort-multiple.ts
  src/helpers/dynamic-sort/dynamic-sort.ts
  src/helpers/empty-to-undefined/empty-to-undefined.ts
  src/helpers/enum-to-array/enum-to-array.ts
  src/helpers/index.ts
  src/helpers/order-array-by/order-array-by.ts
  src/helpers/paginate-array/paginate-array.spec.ts
  src/helpers/paginate-array/paginate-array.ts
  src/helpers/remove-undefined-props/remove-undefined-props.ts
  src/helpers/transform-firestore-types/transform-firestore-types.spec.ts
  src/helpers/transform-firestore-types/transform-firestore-types.ts
  src/helpers/unique-keys-from-array/unique-keys-from-array.ts
  src/tests/integration/NoSqlEasy.spec.ts
  src/types/Filter.ts
  src/types/Options.ts
  src/types/Where.ts
  src/types/index.ts
Labels: PR: reviewed-approved, release:patch

#36 refactor: adjust pull from master
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
Labels: PR: partially-approved, release:patch

#34 Feature/add transaction
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
  src/tests/integration/NoSqlEasy.spec.ts
  src/types/Transaction.ts
  src/types/index.ts
Labels: PR: partially-approved, release:minor

#37 Refactor/transaction to get collections compound
  README.md
  src/dialects/Firestore/FirestoreRepository.ts
  src/index.ts
  src/interfaces/IRepository.ts
  src/tests/integration/NoSqlEasy.spec.ts
Labels: PR: unreviewed, release:patch

#38 Feature/add filter to get size collection
  src/dialects/Firestore/FirestoreRepository.ts
  src/tests/integration/NoSqlEasy.spec.ts
Labels: PR: partially-approved, release:patch
